POST http://localhost:8080/json/data
Content-Type: application/json

{
  "name": "张三",
  "age": 18,
  "gender": "男"
}

###

GET http://localhost:8080/cookie/data
Cookie: cookieName=123456

###

POST http://localhost:8080/user/register
Content-Type: application/json

{
  "name": "admin",
  "password": "123456",
  "age": 12,
  "email": "123456@qq.com",
  "birthday": "2002-02-25"
}